steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$COMMIT_SHA', 'sip_snitch_backend' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$COMMIT_SHA' ]
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [ 'run', 'deploy', '${_SERVICE_NAME}', '--image', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$COMMIT_SHA', '--region', '${_REGION}', '--platform', 'managed' ]

substitutions:
  _REGION: 'europe-west1'
  _SERVICE_NAME: 'sip-snitch-backend-nick'
  _IMAGE_NAME: 'sip-snitch-backend-nick'

options:
  logging: CLOUD_LOGGING_ONLY