name: sip_snitch_backend
description: The backend for the Sip Snitch app.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.6.0

dependencies:
  nanoid2: ^2.0.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0

dev_dependencies:
  http: ^1.1.0
  lint: ^2.3.0
  lints: ^5.0.0
  test: ^1.24.0
